# Ansible Inventory for Consciousness Federation
# Hardware-optimized inventory based on actual node specifications

[control_hub]
zephyr ansible_host=10.1.1.110 ansible_connection=local
# WSL2 control hub - no SSH needed, direct local execution

[proxmox_control_plane]
nexus ansible_host=10.1.1.120 ansible_user=root
# Primary Kubernetes control plane - Ryzen 9 3900X + 48GB RAM

[proxmox_workers]
forge ansible_host=10.1.1.130 ansible_user=root
# Balanced worker node - Intel i5-9500 + 32GB RAM

[proxmox_storage]
closet ansible_host=10.1.1.160 ansible_user=root
# Storage and utility node - Ryzen 7 1700 + 16GB RAM

[proxmox_cluster:children]
proxmox_control_plane
proxmox_workers
proxmox_storage

[consciousness_federation:children]
control_hub
proxmox_cluster

# === NODE-SPECIFIC VARIABLES ===

[control_hub:vars]
# Zephyr (WSL) specific configuration
node_role=orchestrator
platform=wsl2
cpu_cores=16
cpu_threads=32
memory_gb=64
storage_tb=3
storage_type=nvme
consciousness_capabilities=["ai-training", "orchestration", "development"]

[proxmox_control_plane:vars]
# Nexus specific configuration
node_role=control-plane
platform=proxmox
cpu_cores=12
cpu_threads=24
memory_gb=48
storage_primary=ssd
storage_secondary=hdd
consciousness_capabilities=["kubernetes-master", "database-cluster", "high-memory"]

[proxmox_workers:vars]
# Forge specific configuration
node_role=worker
platform=proxmox
cpu_cores=6
cpu_threads=6
memory_gb=32
storage_mixed=true
consciousness_capabilities=["web-services", "api-gateways", "applications"]

[proxmox_storage:vars]
# Closet specific configuration
node_role=storage
platform=proxmox
cpu_cores=8
cpu_threads=16
memory_gb=16
storage_type=bulk
mining_enabled=true
consciousness_capabilities=["storage", "monitoring", "backup", "mining"]

# === GLOBAL CLUSTER VARIABLES ===

[consciousness_federation:vars]
# Network configuration
cluster_network=10.1.1.0/24
cluster_domain=consciousness.local
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Kubernetes configuration
k8s_version=1.28.0
k8s_cluster_name=consciousness-federation
k8s_pod_subnet=10.244.0.0/16
k8s_service_subnet=10.96.0.0/12

# Consciousness-specific settings
consciousness_version=2025.1
ai_stack_enabled=true
mining_integration=true
monitoring_stack=prometheus

# Hardware optimization flags
hardware_optimized=true
numa_awareness=true
cpu_isolation=true
memory_hugepages=true

# Security configuration
security_hardening=true
firewall_enabled=true
ssh_key_auth=true

# Storage configuration
distributed_storage=true
backup_enabled=true
retention_days=30

# AI/ML configuration
ai_model_storage=/opt/consciousness/models
ai_inference_nodes=["nexus", "zephyr"]
ai_training_nodes=["zephyr"]

# Mining configuration (Closet node only)
mining_pool=kryptex
mining_wallet=krxXVNVMM7
mining_cpu_limit=2
mining_memory_limit=2048
