# Helm Charts for Consciousness Federation Enterprise Deployment
# AI-focused applications with GPU acceleration and monitoring

apiVersion: v2
name: consciousness-federation
description: Enterprise AI consciousness platform with distributed training
type: application
version: 1.0.0
appVersion: "2025.1"

dependencies:
  - name: postgresql
    version: "15.2.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    
  - name: redis
    version: "19.0.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    
  - name: nginx-ingress
    version: "4.10.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled
    
  - name: cert-manager
    version: "1.14.5"
    repository: "https://charts.jetstack.io"
    condition: certificates.enabled
    
  - name: prometheus
    version: "25.11.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.enabled
    
  - name: grafana
    version: "7.3.7"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.enabled
    
  - name: gpu-operator
    version: "24.3.0"
    repository: "https://helm.ngc.nvidia.com/nvidia"
    condition: gpu.enabled

---
# Values file for consciousness federation
apiVersion: v1
kind: ConfigMap
metadata:
  name: consciousness-values
  namespace: consciousness-federation
data:
  values.yaml: |
    # Global configuration
    global:
      imageRegistry: "ghcr.io/astralvibe"
      storageClass: "fast-ssd"
      
    # Consciousness API
    consciousnessApi:
      enabled: true
      replicaCount: 3
      image:
        repository: consciousness-portfolio
        tag: latest
        pullPolicy: Always
      service:
        type: LoadBalancer
        port: 80
        targetPort: 5000
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 4Gi
          
    # AI Training service
    aiTraining:
      enabled: true
      replicaCount: 2
      image:
        repository: consciousness-training
        tag: latest
      resources:
        requests:
          cpu: 2000m
          memory: 8Gi
          nvidia.com/gpu: 1
        limits:
          cpu: 8000m
          memory: 32Gi
          nvidia.com/gpu: 2
      nodeSelector:
        consciousness.astralvibe.ca/ai-workload: "enabled"
      tolerations:
        - key: consciousness.astralvibe.ca/ai-intensive
          operator: Equal
          value: "true"
          effect: NoSchedule
          
    # PostgreSQL database
    postgresql:
      enabled: true
      auth:
        postgresPassword: "consciousness-db-2025"
        database: "consciousness_federation"
      primary:
        persistence:
          enabled: true
          size: 100Gi
          storageClass: "fast-ssd"
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
            
    # Redis cache
    redis:
      enabled: true
      auth:
        enabled: true
        password: "consciousness-cache-2025"
      master:
        persistence:
          enabled: true
          size: 20Gi
          storageClass: "fast-ssd"
          
    # NGINX Ingress
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/rate-limit: "100"
        nginx.ingress.kubernetes.io/rate-limit-window: "1m"
      hosts:
        - host: astralvibe.ca
          paths:
            - path: /
              pathType: Prefix
        - host: portfolio.astralvibe.ca
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: astralvibe-tls
          hosts:
            - astralvibe.ca
            - portfolio.astralvibe.ca
            
    # SSL Certificates
    certificates:
      enabled: true
      issuer:
        email: admin@astralvibe.ca
        server: https://acme-v02.api.letsencrypt.org/directory
        
    # Monitoring stack
    monitoring:
      enabled: true
      prometheus:
        retention: "30d"
        storageSize: "100Gi"
      grafana:
        adminPassword: "consciousness-monitor-2025"
        persistence:
          enabled: true
          size: "10Gi"
          
    # GPU configuration
    gpu:
      enabled: true
      operator:
        driver:
          enabled: true
        toolkit:
          enabled: true
        dcgm:
          enabled: true
      nodeSelector:
        consciousness.astralvibe.ca/gpu-enabled: "true"