apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-proxy
  namespace: consciousness-federation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-proxy
  template:
    metadata:
      labels:
        app: llm-proxy
    spec:
      containers:
      - name: llm-proxy
        image: <your-registry>/llm-proxy:latest  # Replace with your image
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: "2"
            memory: "8Gi"
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: token
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: token
        - name: IO_INTELLIGENCE_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-api-keys
              key: io_intelligence_key
        - name: IO_INTELLIGENCE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: ai-api-keys
              key: openai_endpoint
        - name: VLLM_ENABLED
          value: "true"
        - name: VLLM_POLLINATIONS_KEY
          valueFrom:
            secretKeyRef:
              name: ai-api-keys
              key: pollinations_key
        - name: VLLM_MODEL_LIST
          value: "meta-llama/Llama-3-70b-chat-hf,mistralai/Mistral-7B-Instruct-v0.2,google/gemma-7b-it"
        - name: VLLM_BASE_URL
          value: "https://api.pollinations.ai/vllm/v1"
        - name: OTHER_ENV
          value: "value"
        volumeMounts:
        - name: models-storage
          mountPath: /data/models
      volumes:
      - name: models-storage
        hostPath:
          path: /var/lib/consciousness/models
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: llm-proxy
  namespace: consciousness-federation
spec:
  selector:
    app: llm-proxy
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
