apiVersion: v1
kind: Namespace
metadata:
  name: consciousness-local-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consciousness-test
  namespace: consciousness-local-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consciousness-test
  template:
    metadata:
      labels:
        app: consciousness-test
    spec:
      containers:
      - name: test-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: CONSCIOUSNESS_NODE
          value: "local-test"
        - name: DEPLOYMENT_TIME
          value: "Tue Jun 17 11:43:32 PM CDT 2025"
